#!/usr/bin/ruby

# btrfs_subvols -- a munin plugin.
# <chrisjohntapp@gmail.com>

require 'ptools'
require 'sys-filesystem'
include Sys

unless (btrfs_bin = File.which('btrfs'))
  raise RuntimeError, "Can't find btrfs binary"
end

# Probe for btrfs filesystems and populate hash keys with their mount points.
btrfs_vols = Hash.new
Filesystem.mounts do |m|
  if m.mount_type == 'btrfs'
    btrfs_vols[m.mount_point] = nil
  end
end

# If 'config', show graph structure.
if ARGV[0] == 'config'
  puts "graph_title Number of subvolumes per btrfs filesystem"
  puts "graph_vlabel Number of subvolumes"
  puts "graph_category disk"
  btrfs_vols.each do |k,v|
    puts 'vol_' + k + '.label ' + k
  end
  exit 0
end

# Insert number of subvolumes in each case to hash.
btrfs_vols.each do |k,v|
  btrfs_vols[k] = `#{btrfs_bin} subvolume list #{k} | wc -l`.chomp
end

# Print results.
btrfs_vols.each do |k,v|
  puts 'vol_' + k + '.value ' + v
end
